//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Warehouse/Input/PlayerControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;


    public partial class @PlayerControl: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @PlayerControl()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControl"",
    ""maps"": [
        {
            ""name"": ""Basic"",
            ""id"": ""c444f300-2d97-4138-8b7e-114ce16547cf"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""96e1d996-dd30-4b89-a728-fcde466ba1a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShortJump"",
                    ""type"": ""Button"",
                    ""id"": ""36307c04-1b5c-419c-b22b-c7dfd26e6981"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=1)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6767034e-ccdd-4076-b3e8-56ac8f636434"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Attack1"",
                    ""type"": ""Button"",
                    ""id"": ""6380e437-4eec-4803-a82c-35f2669d238c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack2"",
                    ""type"": ""Button"",
                    ""id"": ""9bca4b88-7a6f-4cbc-b3cb-1412ff18ec08"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""bd9dc166-8321-43eb-9d05-0b333988c779"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""92ef75d1-8b4e-4b3d-85d6-8f70d6a58574"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""79e0e838-0499-488b-9cdb-840a9df0540e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""84033b21-146f-4c24-8c72-3e00097406dd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""a14ad3e9-36a4-4acd-a565-47364b87c226"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""35815afa-22af-4000-a5c8-56513ad346c0"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a1e9382b-4a67-41cc-ba56-401662532a47"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""e8e2bac2-6bce-4310-81c7-4b67d6de395d"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShortJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""56fc4306-b1cd-4e59-8744-8d96df269776"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73f2d9e8-be94-4273-a851-0e7cb84290fd"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Basic
            m_Basic = asset.FindActionMap("Basic", throwIfNotFound: true);
            m_Basic_Jump = m_Basic.FindAction("Jump", throwIfNotFound: true);
            m_Basic_ShortJump = m_Basic.FindAction("ShortJump", throwIfNotFound: true);
            m_Basic_Move = m_Basic.FindAction("Move", throwIfNotFound: true);
            m_Basic_Attack1 = m_Basic.FindAction("Attack1", throwIfNotFound: true);
            m_Basic_Attack2 = m_Basic.FindAction("Attack2", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Basic
        private readonly InputActionMap m_Basic;
        private List<IBasicActions> m_BasicActionsCallbackInterfaces = new List<IBasicActions>();
        private readonly InputAction m_Basic_Jump;
        private readonly InputAction m_Basic_ShortJump;
        private readonly InputAction m_Basic_Move;
        private readonly InputAction m_Basic_Attack1;
        private readonly InputAction m_Basic_Attack2;
        public struct BasicActions
        {
            private @PlayerControl m_Wrapper;
            public BasicActions(@PlayerControl wrapper) { m_Wrapper = wrapper; }
            public InputAction @Jump => m_Wrapper.m_Basic_Jump;
            public InputAction @ShortJump => m_Wrapper.m_Basic_ShortJump;
            public InputAction @Move => m_Wrapper.m_Basic_Move;
            public InputAction @Attack1 => m_Wrapper.m_Basic_Attack1;
            public InputAction @Attack2 => m_Wrapper.m_Basic_Attack2;
            public InputActionMap Get() { return m_Wrapper.m_Basic; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(BasicActions set) { return set.Get(); }
            public void AddCallbacks(IBasicActions instance)
            {
                if (instance == null || m_Wrapper.m_BasicActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_BasicActionsCallbackInterfaces.Add(instance);
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @ShortJump.started += instance.OnShortJump;
                @ShortJump.performed += instance.OnShortJump;
                @ShortJump.canceled += instance.OnShortJump;
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Attack1.started += instance.OnAttack1;
                @Attack1.performed += instance.OnAttack1;
                @Attack1.canceled += instance.OnAttack1;
                @Attack2.started += instance.OnAttack2;
                @Attack2.performed += instance.OnAttack2;
                @Attack2.canceled += instance.OnAttack2;
            }

            private void UnregisterCallbacks(IBasicActions instance)
            {
                @Jump.started -= instance.OnJump;
                @Jump.performed -= instance.OnJump;
                @Jump.canceled -= instance.OnJump;
                @ShortJump.started -= instance.OnShortJump;
                @ShortJump.performed -= instance.OnShortJump;
                @ShortJump.canceled -= instance.OnShortJump;
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Attack1.started -= instance.OnAttack1;
                @Attack1.performed -= instance.OnAttack1;
                @Attack1.canceled -= instance.OnAttack1;
                @Attack2.started -= instance.OnAttack2;
                @Attack2.performed -= instance.OnAttack2;
                @Attack2.canceled -= instance.OnAttack2;
            }

            public void RemoveCallbacks(IBasicActions instance)
            {
                if (m_Wrapper.m_BasicActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IBasicActions instance)
            {
                foreach (var item in m_Wrapper.m_BasicActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_BasicActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public BasicActions @Basic => new BasicActions(this);
        public interface IBasicActions
        {
            void OnJump(InputAction.CallbackContext context);
            void OnShortJump(InputAction.CallbackContext context);
            void OnMove(InputAction.CallbackContext context);
            void OnAttack1(InputAction.CallbackContext context);
            void OnAttack2(InputAction.CallbackContext context);
        }
    }
